### PR TITLE
Added support for enums

### LINKED ISSUE #8: Support enums
Add support for [enums](https://docs.python.org/3/library/enum.html) in type fitting.

Example code:

```python
from enum import Enum
from typefit import typefit

class Color(Enum):
    red = 1
    green = 2
    blue = 3

assert typefit(Color, 2) == Color.green
```

### PR DESCRIPTION
**Pull request by sunitdeshpande**
closes #8

### CODE REVIEW

**Comment by Xowap** [comment]
Awesome :tada: 

Thanks! Looks good, I'll test it and merge :)

**Comment by sunitdeshpande** [comment]
Thanks for merging the request. If possible can you please add a description of other issues as well I would love to contribute more.

**Comment by Xowap** [comment]
I'll describe everything then :)

Also don't hesitate to create issues if you think of features you'd like to see there

**Comment by Xowap** [comment]
@sunitdeshpande I've created a Slack channel to discuss things, if you want to join: https://typefit.slack.com

**Comment by Xowap** [comment]
Oh damn you can't make public Slack invites, well tell me if you want to join

**Comment by sunitdeshpande** [comment]
@Xowap please add me to slack channel, my email id is sunitdeshpande1234@gmail.com.

**Pull request merged**
